### ISSUE TITLE
pb fichier hostapd

### ISSUE THREAD

**Issue by 19emtuck** [GLMF/GLMF189#1]
le fichier contient des \r\n ce qui donne la nausée à hostapd et fausse tout le tutorial
présent dans le linux mag. Malheureusement seul '\n' est accepté.

Ceci se caractérise par des erreurs sur des valeurs correctement écrites mais où hostapd
ajoute le '\r' et les déclares fausses

**Comment by tcolombo** [comment]
$ tr "\r" " " < HermesAP.conf
C'est réglé et la présence de ce '\r' est bien étrange... Merci de l'avoir signalé
